### ISSUE TITLE
Was this ever intended to work with vital checks that are asynchronous?

### ISSUE THREAD

**Issue by naemono** [TomFrost/node-vitalsigns#7]
I've been struggling to get this to function properly with a health check that's asynchronous.  I don't know if it's my lack of experience with promises/deferred, or a design issue with vitalsigns.  

When running the below code, I can never get a failure, I only get this:

```
> vitals.getReport();
{ tempfile: { filesystem: [object Object] },
  healthy: true }
> no error /var/folders/bs/f7_wdf1j1y37n64dffw0j379g5rxbj/T/115124-55416-1kag77i
healthy: false
```

And in my browser this:

```
{
tempfile: {
filesystem: { }
},
healthy: true
}
```

Code

```
var express = require("express");
var app = express();
var temp = require('temp');
var q = require('q');

temp.track();

//var temphealthy = true;

var VitalSigns = require('vitalsigns'),
    vitals = new VitalSigns();

function checkTempFile() {

  var p = q.defer(),
    healthy = true;

  temp.open('test-temp-file', function(err, info) {
    if (!err) {
      console.log("no error " + temp.path());
      // I'm trying to force a failure here....
      healthy = false;
      p.resolve(healthy);
    } else {
      console.log("error");
      healthy = false;
      p.resolve(healthy);
    }
  });

  return p.promise;

}

vitals.monitor({
    filesystem: function() {
      return checkTempFile().then( function (healthy) {
        console.log("healthy: " + healthy);
        return healthy;
      });
    }
}, {name: 'tempfile'});

vitals.unhealthyWhen('tempfile', 'filesystem').equals(false);

app.get('/health', vitals.express);

app.listen(3000);
```

Any pointers you could provide would be greatly appreciated.

Thanks

**Comment by TomFrost** [comment]
The idea behind vitalsigns is that, ultimately, a load balancer or managed DNS provider's health check system should be hitting your health endpoint fairly frequently.  Generally you want that call to be absolutely as light and nonimpactful as possible, so that using vitalsigns doesn't weigh down your application at all.  If you were firing off an async call (especially hitting your hard disk) each time this happened, that would have a measurable load.  Imagine if all monitors did asynchronous work all at the same time while the CPU and tick measurements were happening -- every single time you got a report, those other stats would be artificially low.

Instead, what monitors like the tick and cpu monitors do is that, rather than calculate their metrics on request and call back with the result, they run at a set interval and save their result to be passed back synchronously in report requests. That interval is designed to be frequent enough that reports are reliably accurate, without being so frequent that it generates noticeable overhead.

I'd recommend the same thing here -- run checkTempFile with an interval frequency that makes sense given how quickly its result can change, and store that in a local variable to spit out in your 'filesystem' function.  Then, even if checkTempFile _does_ generate load, it becomes extremely predictable.

Does that make sense for your use case?

**Comment by naemono** [comment]
Thanks a ton, that nudged me in the right direction.  

Final set of files (for anyone after me hitting the same wall)

https://gist.github.com/naemono/9f6254764340d4744da1
